name: firebase_auth_starter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.5.0
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.0
  cloud_firestore: ^6.8.0
  email_validator: ^3.0.0
  flutter_bloc: ^9.1.1
  app_links: ^7.0.0
  shared_preferences: ^2.5.5
  equatable: ^2.1.0
  flutter_secure_storage: ^11.0.0
  flutter_svg: ^2.3.0
  firebase_storage: ^13.5.0
  image_picker: ^1.2.3
  flutter_image_compress: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - images/avataar_ben.png
    - images/fire_starter.svg
